site_name: Made With ML
repo_url: https://github.com/arsalanhabib01/driver_detection_fatigue/
nav:
  - mlops:
    - data: mlops/data.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes
