name: documentation
on:
  push:
    branches:
    - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # Set up dependencies
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: python3 -m pip install mkdocs==1.4.2 mkdocstrings==0.21.2 "mkdocstrings[python]>=0.18"

      - name: Set up Git credentials
        run: |
          git config --global user.email "arsalan_dx@hotmail.com"
          git config --global user.name "Arsalan Habib"
          git remote set-url origin https://$GH_TOKEN@github.com/arsalanhabib01/driver_detection_fatigue.git
          
      # Deploy docs
      - name: Deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
      
